server:
  port: 8099
spring:
  application:
    name: task-center
  datasource:
    url: jdbc:mysql://192.168.11.130:3306/dmp_task_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.11.130
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
  redis:
    host: 192.168.11.130
  jackson:
    time-zone: GMT+8


eureka:
  client:
    fetch-registry: false # 不注册自己
    register-with-eureka: false  # 不去注册中心获取其他服务的地址

logging:
  level:
    com.fisk.chartvisual.mapper: debug
    org.springframework.orm.jpa: debug
  config: classpath:logback-spring.xml
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null
      update-strategy: not_null
      logic-delete-field: del_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-enum-type-handler: com.fisk.common.mybatis.config.BaseEnumTypeHandler
#  type-aliases-package: com.fisk.user.entity  实体类的包扫描