spring:
  datasource:
    url: jdbc:mysql://192.168.21.13:3306/dmp_datainput_db_UAT?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Password01!
    driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      datasource:
        taskdb:
          url: jdbc:mysql://192.168.21.13:3306/dmp_task_db_UAT?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: root
          password: Password01!
          driver-class-name: com.mysql.jdbc.Driver

# redis
  redis:
    host: 192.168.21.13
# 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true
# pdf文档模板
dataservice:
  pdf:
    path: /root/java/fisk-factory-access/pdf
    # 接口文档中的环境信息
    uat_address: http://192.168.21.13:8083/{apiaddress}。
    prd_address: https://prdHost/{apiaddress}。

# pg数据源配置
pgsql-datamodel:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.168.21.13:5432/dmp_dw_UAT?stringtype=unspecified
  username: postgres
  password: PgPassword01!
pgsql-ods:
  url: jdbc:postgresql://192.168.21.13:5432/dmp_ods_UAT?stringtype=unspecified
  username: postgres
  password: PgPassword01!