spring:
  datasource:
    url: jdbc:mysql://192.168.21.13:3306/dmp_datainput_db_UAT?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Password01!
    driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      datasource:
        taskdb:
          url: jdbc:mysql://192.168.21.13:3306/dmp_task_db_UAT?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: root
          password: Password01!
          driver-class-name: com.mysql.jdbc.Driver

# redis
  redis:
    host: 192.168.21.13
# 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true
# pdf文档模板
dataservice:
  pdf:
    path: /root/java/fisk-factory-access/pdf
    # 接口文档中的环境信息
    uat_address: http://192.168.21.13:8083
    prd_address: https://prdHost

# pg数据源配置
pgsql-datamodel:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.168.21.13:5432/dmp_dw_UAT?stringtype=unspecified
  username: postgres
  password: PgPassword01!
pgsql-ods:
  url: jdbc:postgresql://192.168.21.13:5432/dmp_ods_UAT?stringtype=unspecified
  username: postgres
  password: PgPassword01!

# 数据质量校验的信息(ip: pg数据源的ip地址; dbName: 连接的ods库)
Data-quality-check:
  ip: 192.168.21.13
  db-name: dmp_ods_UAT

# 元数据实例信息
metadata-instance:
  # 数据库类型
  rdbmsType: postgresql
  # 平台
  platform: Linux
  # 主机
  hostname: 192.168.21.13
  # 端口
  port: 5432
  # 数据库
  dbName: dmp_ods_UAT
  # 网络协议
  protocol: http

flink-config:
  host: 192.168.11.131
  port: 22
  user: root
  password: Password01!
  upload-path: /root/flink-job/sql/
  upload-way: ssh
  savepoints-path: /root/flink-job/savepoint/
  command: dev
  command-path: /root/flink/flink-1.15.2/bin/sql-client.sh

flink-api-config:
  host: http://192.168.11.131
  port: 8081
  savepoints: /jobs/:jobid/savepoints
  savepoint-status: /jobs/:jobid/savepoints/:triggerid