dataquality:
  excel:
    # excel保存路径
    path: /data/java/fisk-governance-center/dataquality/excel
dataops:
  # pg数据库元数据对应 redis key
  pg_metadataentity_key: DataOps_PGMetaDataEntityKey
  # 执行时间 凌晨12点半
  schedule: 0 30 0 * * ?
  # 是否启用
  enabled: true
spring:
  application:
    name: datagovernance-service
  datasource:
    url: jdbc:mysql://10.220.108.140:13307/dmp_datagovernance_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: .FdF_r&tj4)+
    driver-class-name: com.mysql.jdbc.Driver
  # redis
  redis:
    host: 10.220.108.140
    port: 16380
    password: test123456
# pg数据源配置
pgsql-dw:
  id: 1
  ip: 100.102.201.107
  port: 5433
  dbName: dmp_dw
  url: jdbc:postgresql://100.102.201.107:5433/dmp_dw?stringtype=unspecified #&connectTimeout=60&socketTimeout=60超时等待60s
  username: adminuser
  password: .FdF_r&tj4)+
  driverClassName: org.postgresql.Driver
pgsql-ods:
  id: 2
  ip: 100.102.201.107
  port: 5433
  dbName: dmp_ods
  url: jdbc:postgresql://100.102.201.107:5433/dmp_ods?stringtype=unspecified #&connectTimeout=60&socketTimeout=60超时等待60s
  username: adminuser
  password: .FdF_r&tj4)+
  driverClassName: org.postgresql.Driver
pgsql-mdm:
  id: 3
  ip: 100.102.201.107
  port: 5433
  dbName: dmp_mdm
  url: jdbc:postgresql://100.102.201.107:5433/dmp_mdm?stringtype=unspecified #&connectTimeout=60&socketTimeout=60超时等待60s
  username: adminuser
  password: .FdF_r&tj4)+
  driverClassName: org.postgresql.Driver
file:
  uploadUrl: /root/nginx/app/file/qualityreport/
  echoPath: /file/qualityreport/