server:
  port: 8089
spring:
  application:
    name: dataAccess-service
  datasource:
    url: jdbc:mysql://192.168.11.130:3306/dmp_datainput_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 192.168.11.130
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss

fk:
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid .
      strength: 6 # 加密强度4~31，决定盐加密时的运算强度，超过10以后加密耗时会显著增加

  # 配置此条信息,当前服务开启时会调用feign接口,去授权中心获取秘钥
  auth:
    clientId: dataAccess-service
    secret: 1234
#    includeFilterPaths:
#      - /appRegistration/** # 拦截用户信息


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka
logging:
  level:
    com.fisk.dataaccess: debug
    org.springframework.orm.jpa: debug
mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 主键以用户插入为准
      insert-strategy: not_null
      update-strategy: not_null
      logic-delete-field: del_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fisk.dataaccess.entity  # 实体类的包扫描
  configuration:
    default-enum-type-handler: com.fisk.common.mybatis.config.BaseEnumTypeHandler
#feign:
#  hystrix:
#    enabled: true