spring:
  application:
    name: license-registry
  datasource:
    url: jdbc:mysql://192.168.11.130:3306/dmp_license_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.11.130