spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.21.21:3306/dmp_system_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
  redis:
    host: 192.168.21.21
    password: test123456
# mdm授权账号
mdmAuthorize:
  url: http://fidata.fisksoft.com:65123/api/Integration/GetToken
  userAccount: admin
  userPassword: 123456
# 图片上传
file:
  uploadurl: /root/static/file/dmp/images
  logoUrl: /root/static/file/systemlogo/images
