spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.21.21:3306/dmp_system_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123

  redis:
    host: 192.168.21.21
    password: test123456

# 图片上传
file:
  uploadurl: /root/nginx/app/file/dmp/images
