spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.195.131.25:3306/dmp_system_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: nifi_owner
    password: ABCabc1234

  redis:
    host: 10.195.131.21
    port: 6379
    password: 7b80ba2c

# 图片上传
file:
  uploadurl: /root/nginx/app/file/dmp/images
  logoUrl: /root/nginx/app/file/systemlogo/images
