spring:
  application:
    name: data-factory
  datasource:
    url: jdbc:mysql://192.168.21.21:3306/dmp_datafactory_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.21.21
    password: test123456