datamodeldorisconstr:
  driver_class_name: com.mysql.jdbc.Driver
  password: Password01!
  url: jdbc:mysql://192.168.11.134:9030/dmp_olap?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
  username: root

external-table-link: '"host" = "192.168.1.250","port" = "5432","user" = "postgres","password"
  = "Password01!","database" = "dmp_dw"'

nifi:
  basePath: https://10.178.188.31:8443/nifi-api
  username: fisk
  password: fiskpassword01!
  token: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkMjc2Mjk3N2U4YjU0YTQ0YjYyZGU2ODlmZTk0OTRjNiIsInVzZXIiOiJ7XCJpZFwiOjE4LFwidXNlckFjY291bnRcIjpcImNma1wifSIsImlkIjoiMTgifQ.SRkIbNgKrvo1TI-WSufy4mZGLst6ed0Y6Fs0QoQ8m_g
  Enable-Authentication: 1
  kerberos:
    Keytab: /opt/fidata/java/fisk-task-center/kafka.keytab
    login:
      config: /opt/fidata/java/fisk-task-center/kafka-jaas.conf
    krb5:
      conf: /opt/fidata/java/fisk-task-center/krb5.conf
  kerberosprincipal: kafka/admin@AUTOEXPR.COM


  pipeline:
    topicName: task.build.task.publish
    waitTime: 30
    operation-interval: 2000
    number-of-operations: 5
    data-governance-url: http://10.178.188.31:8083
nifi-ConcurrentTasks: 1
nifi-FetchSize: 10000
nifi-MaxRowsPerFlowFile: 10000
nifi-OutputBatchSize: 1
fiData-data-ods-source: 2
fiData-data-dw-source: 1

pgsql-datamodel:
  driverClassName: org.postgresql.Driver
  password: Password01!
  url: jdbc:postgresql://192.168.1.250:5432/dmp_dw?stringtype=unspecified
  username: postgres
  ip: 192.168.1.250
  dbName: dmp_dw
pgsql-mdm:
  password: Password01!
  url: jdbc:postgresql://192.168.1.250:5432/dmp_mdm?stringtype=unspecified
  username: postgres
  type: PG
server:
  port: 7003
spring:
  application:
    name: task-center
  datasource:
    dynamic:
      datasource:
        datainputdb:
          driver-class-name: com.mysql.jdbc.Driver
          password: Fisksoft@hsd06
          url: jdbc:mysql://10.178.188.31:3306/dmp_datainput_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: fisksoft
        taskdb:
          driver-class-name: com.mysql.jdbc.Driver
          password: Fisksoft@hsd06
          url: jdbc:mysql://10.178.188.31:3306/dmp_task_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: fisksoft
      primary: taskdb
      strict: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  kafka:
    consumer:
      bootstrap-servers: 10.178.188.70:9092
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      session:
        timeout:
          ms: 300000
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: 0
      bootstrap-servers: 10.178.188.70:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: 10.178.188.65:9092,10.178.188.70:9092,10.178.188.92:9092
  redis:
    host: 10.178.188.31
    password: redis@test
    port: 6379
