dataservice:
  pdf:
    # pdf文档模板路径
    path: /root/java/fisk-consume-serveice/pdf
    # 接口文档中的环境信息
    api_address: http://192.168.21.13:8083/{apiaddress}。
  datasource:
    # redis key
    metadataentity_key: DataService_MetaDataKey
    # 执行时间 凌晨12点半
    schedule: 0 55 16 * * ?
    # 是否启用
    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Password01!
    url: jdbc:mysql://192.168.21.13:3306/dmp_dataservice_db_UAT?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
  # redis 获取用户需要使用到
  redis:
    host: 192.168.21.13
  # 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true