dataservice:
  pdf:
    # pdf文档模板路径
    path: /root/java/fisk-consume-serveice/pdf
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Password01!
    url: jdbc:mysql://192.168.21.13:3306/dmp_dataservice_db_UAT?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
  # redis
  redis:
    host: 192.168.21.13
  # 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true